### ISSUE TITLE
Math with $(( )) syntax

### ISSUE THREAD

**Issue by eugenenuke** [seankross/the-unix-workbench#117]
I wonder why you didn't mention another bash syntax for math. It is easier to use than _let_ or _expr_.
**var=$(( x + y ))** vs **let var=x+y** . In the first case I'm free to use spaces the second one is stricter.
And one more moment: _expr_ isn't a bash command it's external command from gnu coreutils package.

**Comment by seankross** [comment]
> I wonder why you didn't mention another bash syntax for math.

I wanted to make a choice and minimize the number of redundant concepts in the book.

> ...expr isn't a bash command it's external command from gnu coreutils package.

This information isn't relevant to newcomers to the command line so I didn't mention it.
