### ISSUE TITLE
Is it clean or clear command? 

### ISSUE THREAD

**Issue by narenatgit** [seankross/the-unix-workbench#2]
Hi, 

Thanks for putting up this book for a novice like me. Really appreciate the efforts. I was reading though 03-Command-Line-Basics.Rmd and found that 'clean' is mentioned as command to clear the screen. And down the line after a para it is mentioned that 'clear' is for same purpose. 

Are both used to clear the screen or one of them? 

Thanks!

**Comment by seankross** [comment]
Hi @narenatgit, it's definitely `clear`! I'll fix that typo right now. I'm glad you're finding it useful, if you have any other questions or comments let me know.
