### ISSUE TITLE
egrep doesn't recognize \d and \s metacharacters

### ISSUE THREAD

**Issue by davidblitz** [seankross/the-unix-workbench#225]
I'm using bash under ubuntu 16.04 and the corresponding examples (https://github.com/seankross/the-unix-workbench/blob/master/04-Working-with-Unix.Rmd#character-sets) work only with ack.

**Comment by archqua** [comment]
For some reason egrep really does some freaking nonsense with \d metacharacter.
What's fun, when I was deleting egrep "<smth>\d<smth>" from bash script in vim using 
```
:% s/\d/[0-9]/g
```
vim recognized /d as a metacharacter and did not what I wanted.

**Comment by nakulGoyal19** [comment]
$ grep -P "\d" small.txt
 
This works fine.
