### ISSUE TITLE
ubuntu uses .profile instead of .bash_profile

### ISSUE THREAD

**Issue by davidblitz** [seankross/the-unix-workbench#226]
I created .bash_profile when I was going through the "configure" section (https://github.com/seankross/the-unix-workbench/blob/master/04-Working-with-Unix.Rmd#configure) but then the .bash_profile wasn't sourced after reboot.

**Comment by seankross** [comment]
As far as I know that is unusual, and it might have to do with how you have other startup scripts or variables configured. From what I understand `~/.bash_profile` is sourced if it is present, in which case `~/.profile` is not sourced. You can find more information here: https://askubuntu.com/questions/510709/i-cannot-find-bash-profile-in-ubuntu
